services:
  backend:
    build:
      context: ./expressjs-and-rest-nikhildevarakonda320
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./my-app.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:5020